baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Chris Ried Blog"
theme = "hugo-theme-noteworthy"
googleAnalytics = "UA-100452126-1"
disqusShortname = "cbayes" 
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "Resume"
    url = "/resume/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cdr6934"
[[menu.main]]
    name = "Medium"
    url = "https://medium.com/@cdr6934"
[[menu.main]]
    name = "Photography"
    url = "https://unsplash.com/@cdr6934"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/cdr6934"
[[menu.main]]
    name = "Consulting"
    url = "/consulting/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"


[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
    # Main
    email = "chris@cbayes.com"
    facebook = "https://www.facebook.com/christopher.ried/"
    twitter = "https://twitter.com/cdr6934"
    instagram = "https://www.instagram.com/generate.collective/"
    #tumblr = "#"
    reddit = "https://www.reddit.com/user/digitalbro"
    #pinterest = "#"
    #youtube = "#"
    #vimeo = "#"
    #weibo = "#"
    #vk = "#"
    linkedin = "https://www.linkedin.com/in/chrisried/"
    
    # Writing
    medium = "https://medium.com/@cdr6934"
    #blogger = "#"
    #wordpress = "#"
    
    # Creative & Visual
    #dribbble = "#"
    #behance = "#"
    #deviantart = "#"
    #flickr = "#"
    
    # Audio & Music
    soundcloud = "https://soundcloud.com/chris_ried"
    
    # Programming
    github = "https://github.com/cdr6934"
    stackoverflow = "https://stackoverflow.com/users/862808/c-ried"
    #gitlab = ""
    #codepen = "#"
    
    # Academic
    googlescholar = "#"
    impactstory = "#"
    orcid = "#"  
