---
title: 'Experiments with Datamuse API '
author: Chris
date: '2018-01-03'
slug: experiments-with-datamuse-api
categories:
  - R
  - generative text
tags: []
---

# IN Progress
words with a meaning similar to ringing in the ears							            https://api.datamuse.com/words?ml=ringing+in+the+ears
words related to duck that start with the letter b							            https://api.datamuse.com/words?ml=duck&sp=b*
words related to spoon that end with the letter a							              https://api.datamuse.com/words?ml=spoon&sp=*a
words that sound like elefint												                        https://api.datamuse.com/words?sl=elefint
words that start with t, end in k, and have two letters in between	        https://api.datamuse.com/words?sp=t??k
words that are spelled similarly to coneticut	                              https://api.datamuse.com/words?sp=coneticut
words that rhyme with forgetful	                                            https://api.datamuse.com/words?rel_rhy=forgetful
words that rhyme with grape that are related to breakfast	                  https://api.datamuse.com/words?ml=breakfast&rel_rhy=grape
adjectives that are often used to describe ocean	                          https://api.datamuse.com/words?rel_jjb=ocean
adjectives describing ocean sorted by how related they are to temperature	  https://api.datamuse.com/words?rel_jjb=ocean&topics=temperature
nouns that are often described by the adjective yellow	                    https://api.datamuse.com/words?rel_jja=yellow
words that often follow "drink" in a sentence, that start with the letter w	https://api.datamuse.com/words?lc=drink&sp=w*
words that are triggered by (strongly associated with) the word "cow"	      https://api.datamuse.com/words?rel_trg=cow
suggestions for the user if they have typed in rawand so far	              https://api.datamuse.com/sug?s=rawand